name: Docker Actions

on:
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: hello-action
        uses: ./.github/actions/hello-world
      - name: meow
        uses: ./.github/actions/cat-facts
        id: cat
      - name: install npm packages
        run: |
          cd ./.github/actions/issue-maker
          npm install
      - name: create-issue
        uses: ./.github/actions/issue-maker
        with:
          repoToken: ${{ github.token }}
          catFact: ${{ steps.cat.outputs.fact }}
          issueTitle: a cat fact for you
